### ISSUE TITLE
Мой отчет о результатах комита

### ISSUE THREAD

**Issue by Kowarchik** [Kowarchik/K13-1-Katash#1]
Я создала папку GitProject, в ней создала файл К13-1 Каташ Кристина Олеговна.txt с текстом. С помощью Git Bush выполнила следующие команды: 
git init 
git add . 
git commit -m "first commit" 
git remote add origin https://github.com/Kowarchik/K13-1-Katash.git
git push -u origin master 
Вот скриншоты:
![1](https://cloud.githubusercontent.com/assets/19518002/15805209/b8e234e2-2b2b-11e6-914d-9da915685b75.jpg)
![2](https://cloud.githubusercontent.com/assets/19518002/15805210/b8e38b76-2b2b-11e6-958b-2490ea79714c.jpg)

**Comment by Smoktii** [comment]
Ок
